### PR TITLE
dask gateway 0.9 compatibility

### PR DESCRIPTION
**Pull request by scottyhq**
this includes some metrics changes and ability to run images that have dask-gateway>=0.9

### CODE REVIEW

**Comment by scottyhq** [comment]
hmmm @TomAugspurger more merge conflict issues, thoughts?

**Comment by TomAugspurger** [comment]
Strange, the changes from staging look correct, if you just want to take those.

**Comment by TomAugspurger** [comment]
Did you test if things look ok with dask-gateway 0.8 in the environment / worker image?

**Comment by TomAugspurger** [comment]
Running http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/ on staging at https://staging.binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/master?urlpath=git-pull?repo=https://github.com/TomAugspurger/pangeo-dask-gateway%26amp%3Burlpath=lab/tree/pangeo-dask-gateway, the cluster failed to start.

So it seems like we will need to update everyone?

**Comment by scottyhq** [comment]
> So it seems like we will need to update everyone? 

Yes, I also see the following traceback with the 2020.10.26 image. Not sure what logs to look at since the scheduler pod disappears, and I couldn't be bothered to look through all the others ;) 

```pytb
---------------------------------------------------------------------------
GatewayClusterError                       Traceback (most recent call last)
<ipython-input-3-16ce7555c8c6> in <module>
      8 options = gateway.cluster_options()
      9 options.environment = env
---> 10 cluster = gateway.new_cluster(options)
     11 cluster.scale(4) # let's get the same number of "workers" as our previous LocalCluster examples

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    633         cluster : GatewayCluster
    634         """
--> 635         return GatewayCluster(
    636             address=self.address,
    637             proxy_address=self.proxy_address,

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, public_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    807         **kwargs,
    808     ):
--> 809         self._init_internal(
    810             address=address,
    811             proxy_address=proxy_address,

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, public_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    912             self.status = "starting"
    913         if not self.asynchronous:
--> 914             self.gateway.sync(self._start_internal)
    915 
    916     @property

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    337             )
    338             try:
--> 339                 return future.result()
    340             except BaseException:
    341                 future.cancel()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _start_internal(self)
    926             self._start_task = asyncio.ensure_future(self._start_async())
    927         try:
--> 928             await self._start_task
    929         except BaseException:
    930             # On exception, cleanup

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _start_async(self)
    944         # Connect to cluster
    945         try:
--> 946             report = await self.gateway._wait_for_start(self.name)
    947         except GatewayClusterError:
    948             raise

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask_gateway/client.py in _wait_for_start(self, cluster_name)
    574                     return report
    575                 elif report.status is ClusterStatus.FAILED:
--> 576                     raise GatewayClusterError(
    577                         "Cluster %r failed to start, see logs for "
    578                         "more information" % cluster_name

GatewayClusterError: Cluster 'staging.d73adbacde4d4c95a6715c7bc0ad2f00' failed to start, see logs for more information
```

**Pull request merged**
