### PR TITLE
staging -> prod (#100 - #114, all dask-gateway related)

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. We'll need to push a few additional items specific to prod here. I'll do that in a little bit.

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/pangeo-binder/pull/116/commits/c2869cc3d8b4c8908fb0e8184a57ab417c65e08b has what we need for prod. Should be good to go.

**Comment by TomAugspurger** [comment]
Didn't quite work on prod. Will investigate more this afternoon.

**Comment by tjcrone** [comment]
I can also help with this later this afternoon. Thanks for moving this forward. @TomAugspurger or @jhamman, can you please describe in general the changes to our secrets?

**Comment by TomAugspurger** [comment]
I'm hopeful that https://github.com/pangeo-data/pangeo-binder/commit/978df45daf666ce91e614291de48dfb58bf1304b fixes things on prod.

---

@tjcrone the following, the tokens filled in as needed

```diff


diff --git a/secrets/prod.yaml b/secrets/prod.yaml
index 55954ab..7e15778 100644
--- a/secrets/prod.yaml
+++ b/secrets/prod.yaml
@@ -4,6 +4,8 @@ binderhub:
         services:
           binder:
             apiToken: "..."
+          dask-gateway:
+            apiToken: "<api-token>"
       proxy:
         secretToken: "..."
   registry:
@@ -23,3 +25,12 @@ binderhub:
       }

+
+
+dask-gateway:
+  gateway:
+    proxyToken: "<proxy-token>"
+    auth:
+      type: jupyterhub
+      jupyterhub:
+        apiToken: "<api-token>"
```

**Comment by TomAugspurger** [comment]
All good now.

**Pull request merged**
