### PR TITLE
Bump dask gateway

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @jcrist.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Going to just merge this to staging. I don't think there's an easy way to test otherwise.

**Comment by TomAugspurger** [comment]
Deploy seemingly went well. Testing with https://github.com/TomAugspurger/pangeo-binder-test.

**Comment by jcrist** [comment]
Note that a 0.7.0 client will *not* work with a 0.6.1 server (and vice-versa). This release adds a versioned api and attempts to stabilize things, so ideally future releases will not be so reliant on exact version matches.

**Comment by jcrist** [comment]
Oh, it's also a brand new helm chart, so the existing helm values will need to be updated. I recommend walking through the updated deploy docs https://gateway.dask.org/install-kube.html.

**Comment by TomAugspurger** [comment]
Thanks. My environment has dask_gateway 0.7.0, (should have) bumped the server to 0.7.0.

But this definitely failed, probably due to helm changes. Will push some more.

**Pull request merged**
