### PR TITLE
Add Prometheus / Grafana

### PR DESCRIPTION
**Pull request by salvis2**
Adds Prometheus and Grafana to the `pangeo-binder` local Helm chart. I tested on my own infrastructure (attempted to Terraform all of the Helm pieces and was unsuccessful), so I followed @scottyhq 's [instructions](https://github.com/pangeo-data/pangeo-binder/blob/staging/k8s-aws/readme.md) for setting up on AWS.

I use the same configuration for both the AWS and GCP BinderHubs but changed the Ingress hosts to be the relevant domains. On that note, we need `prometheus.` and `grafana.` subdomains added to `aws-uswest2-binder.pangeo.io` and `binder.pangeo.io`. The A records' targets should be the result of

```
kubectl get svc prod-nginx-ingress-controller -n prod
```

at least in the AWS case. Unsure if the service would have a different name on the GCP side. These should be in place before we deploy Prometheus and Grafana. I'm not sure where these live (it looks like they live together under `pangeo.io`), but they should be quick to setup.
- [x] Add subdomains for AWS BinderHub DNS records
- [x] Add subdomains for GCP BinderHub DNS records

You can check out the testing deployment I ran. I can launch [this gallery repo](https://github.com/pangeo-data/landsat-8-tutorial-gallery) via https://test-binder.hackweek.io/ and watch the [default enabled monitoring dashboard](https://grafana.test-binder.hackweek.io/d/JABGX_-mz/cluster-monitoring-for-kubernetes?orgId=1&refresh=10s). This is enabled [on these lines](https://github.com/pangeo-data/pangeo-binder/pull/155/files#diff-590371a4912f3ac827ca1b75524c8582R353-R358) (the dashboard is ID 10000).

I will leave up the test infrastructure temporarily to demonstrate that it works and to try a couple more tests at a later date to see if I can get the Helm pieces managed by Terraform.

I've only set this up on the `prod` clusters' settings. The monitoring should be able to access all namespaces on the cluster, so it shouldn't matter what namespace it is deployed in. I think it is redundant to deploy it in both `staging` and `prod`. I don't know how that should inform the workflow for fully enabling this.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks for working on this. One note: this uses the separate `grafana` and `prometheus` helm charts, rather than `prometheus-operator` like I used in pangeo-cloud-federation.

I don't recall why I originally went with prometheus-operator. I don't think we're using any of it's additional functionality over the separate helm charts.

**Comment by salvis2** [comment]
@TomAugspurger originally I was hoping to get this done earlier so that @scottyhq could have some usage stats for a webinar he and Anthony are giving next week. As it stands, we don't wanna merge and break anything before then to make sure the BinderHub stays working. I can look into using `pangeo-operator`, this setup was just more familiar to me to start with.

**Comment by salvis2** [comment]
I'm actually getting stuck on doing TLS and HTTPS for the grafana endpoint. My browser blocks me from entering since I'm issuing a fake ingress certificate for it. I haven't been able to get it to let me in with a "Not Secure" warning in my browser. Should be possible though, since grafana.mybinder.org is HTTPS enabled. Still fiddling with how to set values for the Helm charts.

I'm pretty sure the issue is related to the fact that the `hub` and base routes for the BinderHub have `LoadBalancer` services and the `cert-manager` Issuer we configure has its solver as `http01`. Was doing some reading [here](https://cert-manager.io/docs/configuration/acme/http01/) about it. There is another solver, `dns01`, that [can be configured with Route53](https://cert-manager.io/docs/configuration/acme/dns01/route53/) (useful for my test DNS stuff that is on Route 53, but maybe not with that of pangeo.io since it is elsewhere), but seems like a bit more work. I'm currently trying to see if I can deploy Grafana to have a `LoadBalancer` resource, which _should be really easy_, but I haven't gotten it to do this yet with `prometheus-operator`.

**Comment by salvis2** [comment]
I have now learned that the proper value nesting for the subcharts, like Grafana, is

```
prometheus-operator:
  grafana:
    enabled: true
```

Which was unclear, since the values for the `prometheus-operator` Helm chart include a section that looks like `prometheusOperator`... https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus-operator-1

**Comment by salvis2** [comment]
Updates, ping @TomAugspurger @scottyhq 

- `prometheus-operator` is now used. Config is only present on `prod` files for now, seemed redundant to put it on both but I can do that and switch all the `resources` to 0 for staging.
- `grafana` is exposed as a `LoadBalancer` so it can function with the ingress block / `cert-manager` and get HTTPS / TLS like the binderhub. 
  - It currently has just one preset dashboard, ID 10000.
  - It has an admin login in the secrets with a randomized password I generated online.
- `prometheus` is not exposed outside the cluster. Grafana can connect just fine. I tried to make it a `LoadBalancer` the same way `grafana` was, but no dice.
- I added another CNAME record for grafana.aws-uswest2-binder.pangeo.io. It looks like there's already one for grafana.binder.pangeo.io, so I didn't mess with that.

I can put in some config to enable GitHub auth to Grafana (figured out how to do that on the OceanHackWeek cluster's Grafana deployment). Thoughts?

**Comment by TomAugspurger** [comment]
Cool! At least for the GCP cluster we were happy to make the metrics read-only public (https://github.com/pangeo-data/pangeo-cloud-federation/pull/671/commits/425f834a2dc8d9b504558fbc259516cac40aea95).

**Comment by salvis2** [comment]
Updates:
- Put config in for staging binderhubs. Set staging resource requests to 0 for both binderhubs.
- Patched up some things. There was old code in the GCP config I forgot to take out and some incorrect hosts.
- Put in a DNS record for grafana.staging.aws-uswest2-binder.pangeo.io. There was already a GCP equivalent, so I didn't mess with it.

**Comment by salvis2** [comment]
@scottyhq , I went through with your deployment instructions and it was really good for the most part. I ended up switching the `cert-manager` / issuer deployment step with the HTTPS-enabled binderhub step (so the `cert-manager` bit came first). I can't remember if I had an issue that this flip fixed or if it was unrelated and I flipped them as a guess. The [Zero-to-Binderhub docs](https://binderhub.readthedocs.io/en/latest/https.html) recommend this ordering though, so I changed that in the readme as well.

**Comment by TomAugspurger** [comment]
What's the status here @salvis2? Anything I can do to help push things along?

**Comment by salvis2** [comment]
@TomAugspurger I think it was done, barring any desired changes. I deployed the setup on some AWS infrastructure that I Terraform'd.

**Comment by TomAugspurger** [comment]
Cool, let's give it a shot.

**Pull request merged**
